# Generated by Django 4.2.1 on 2023-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20230607_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='internal_contrat_number',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='status',
            field=models.BooleanField(default=False, verbose_name='signé'),
        ),
    ]
