# Generated by Django 4.2.1 on 2023-06-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0002_auto_20230605_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(choices=[(5, 'Vente'), (4, 'Gestion'), (6, 'Support')], max_length=30, to='auth.group', verbose_name='team'),
        ),
    ]
